### ISSUE TITLE
Show hint when loading missing font

### ISSUE THREAD

**Issue by peacememories** [aler9/googlefonts-inliner#9]
Hi, first of all thanks for making this plugin, it's working like a charm :)

One improvement I could think of is, that the plugin could fail with an explicit message when it gets back a 404 from google. I ran into this just now and spent a fair bit of time wondering why there would be "Missing semicolons", because I used the wrong url. Failing explicitly here would make for an even better dev experience :)

**Comment by aler9** [comment]
Thanks for the feedback, now if the font can't be downloaded (status code != 200), a warning is emitted.

**Comment by peacememories** [comment]
Wow, that was incredibly quick! Thanks for adding this :)
